master:
  image: gtmanfred/salt
  ports:
    - 4505:4505
    - 4506:4506
    - 8000
  hostname: salt
  environment:
    - PATH=/root/.pyenv/shims:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - SALT_MASTER=True
    - SALT_API=True
  volumes:
    - ~/github/salt:/srv/gitrepo
    - ./states:/srv/salt
    - ./pillar:/srv/pillar

minion:
  image: gtmanfred/salt
  environment:
    - PATH=/root/.pyenv/shims:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - SALT_MINION=True
  volumes:
    - ~/github/salt:/srv/gitrepo
  links:
    - master:salt

proxy:
  image: gtmanfred/salt
  command: [-l, debug]
  environment:
    - PATH=/root/.pyenv/shims:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - SALT_PROXY=True
  volumes:
    - ~/github/salt:/srv/gitrepo
  links:
    - master:salt
