master:
  build: salt
  ports:
    - 4505:4505
    - 4506:4506
    - 8000
  hostname: salt
  environment:
    - SALT_MASTER=True
    - SALT_API=True
  volumes:
    - ~/github/salt:/srv/salt

minion:
  build: salt
  environment:
    - SALT_MINION=True
  volumes:
    - ~/github/salt:/srv/salt
  links:
    - master:salt
